/**
 * Constituyentes del S&P 500 — universo del monitor de equity.
 *
 * Generado por `node scripts/generar-universo-sp500.mjs` el 2026-08-23.
 * No editar a mano: correr el script cuando el índice cambie.
 *
 * El sector es el GICS del índice y viene acá, no de Yahoo: pedirlo por API
 * costaría un request por ticker y sólo cambia cuando la empresa se reclasifica.
 */
import type { Sector } from "@/lib/equity-sectores";

export interface EmpresaUniverso {
  ticker: string;
  nombre: string;
  sector: Sector;
}

export const UNIVERSO_SP500: EmpresaUniverso[] = [
  { ticker: "A", nombre: "Agilent Technologies", sector: "Health Care" },
  { ticker: "AAPL", nombre: "Apple Inc.", sector: "Information Technology" },
  { ticker: "ABBV", nombre: "AbbVie", sector: "Health Care" },
  { ticker: "ABNB", nombre: "Airbnb", sector: "Consumer Discretionary" },
  { ticker: "ABT", nombre: "Abbott Laboratories", sector: "Health Care" },
  { ticker: "ACGL", nombre: "Arch Capital Group", sector: "Financials" },
  { ticker: "ACN", nombre: "Accenture", sector: "Information Technology" },
  { ticker: "ADBE", nombre: "Adobe Inc.", sector: "Information Technology" },
  { ticker: "ADI", nombre: "Analog Devices", sector: "Information Technology" },
  { ticker: "ADM", nombre: "Archer Daniels Midland", sector: "Consumer Staples" },
  { ticker: "ADP", nombre: "Automatic Data Processing", sector: "Industrials" },
  { ticker: "ADSK", nombre: "Autodesk", sector: "Information Technology" },
  { ticker: "AEE", nombre: "Ameren", sector: "Utilities" },
  { ticker: "AEP", nombre: "American Electric Power", sector: "Utilities" },
  { ticker: "AES", nombre: "AES Corporation", sector: "Utilities" },
  { ticker: "AFL", nombre: "Aflac", sector: "Financials" },
  { ticker: "AIG", nombre: "American International Group", sector: "Financials" },
  { ticker: "AIZ", nombre: "Assurant", sector: "Financials" },
  { ticker: "AJG", nombre: "Arthur J. Gallagher & Co.", sector: "Financials" },
  { ticker: "AKAM", nombre: "Akamai Technologies", sector: "Information Technology" },
  { ticker: "ALB", nombre: "Albemarle Corporation", sector: "Materials" },
  { ticker: "ALGN", nombre: "Align Technology", sector: "Health Care" },
  { ticker: "ALL", nombre: "Allstate", sector: "Financials" },
  { ticker: "ALLE", nombre: "Allegion", sector: "Industrials" },
  { ticker: "AMAT", nombre: "Applied Materials", sector: "Information Technology" },
  { ticker: "AMCR", nombre: "Amcor", sector: "Materials" },
  { ticker: "AMD", nombre: "Advanced Micro Devices", sector: "Information Technology" },
  { ticker: "AME", nombre: "Ametek", sector: "Industrials" },
  { ticker: "AMGN", nombre: "Amgen", sector: "Health Care" },
  { ticker: "AMP", nombre: "Ameriprise Financial", sector: "Financials" },
  { ticker: "AMT", nombre: "American Tower", sector: "Real Estate" },
  { ticker: "AMZN", nombre: "Amazon", sector: "Consumer Discretionary" },
  { ticker: "ANET", nombre: "Arista Networks", sector: "Information Technology" },
  { ticker: "AON", nombre: "Aon plc", sector: "Financials" },
  { ticker: "AOS", nombre: "A. O. Smith", sector: "Industrials" },
  { ticker: "APA", nombre: "APA Corporation", sector: "Energy" },
  { ticker: "APD", nombre: "Air Products", sector: "Materials" },
  { ticker: "APH", nombre: "Amphenol", sector: "Information Technology" },
  { ticker: "APO", nombre: "Apollo Global Management", sector: "Financials" },
  { ticker: "APP", nombre: "AppLovin", sector: "Communication Services" },
  { ticker: "APTV", nombre: "Aptiv", sector: "Consumer Discretionary" },
  { ticker: "ARE", nombre: "Alexandria Real Estate Equities", sector: "Real Estate" },
  { ticker: "ARES", nombre: "Ares Management", sector: "Financials" },
  { ticker: "ATO", nombre: "Atmos Energy", sector: "Utilities" },
  { ticker: "AVGO", nombre: "Broadcom", sector: "Information Technology" },
  { ticker: "AVY", nombre: "Avery Dennison", sector: "Materials" },
  { ticker: "AWK", nombre: "American Water Works", sector: "Utilities" },
  { ticker: "AXON", nombre: "Axon Enterprise", sector: "Industrials" },
  { ticker: "AXP", nombre: "American Express", sector: "Financials" },
  { ticker: "AZO", nombre: "AutoZone", sector: "Consumer Discretionary" },
  { ticker: "BA", nombre: "Boeing", sector: "Industrials" },
  { ticker: "BAC", nombre: "Bank of America", sector: "Financials" },
  { ticker: "BALL", nombre: "Ball Corporation", sector: "Materials" },
  { ticker: "BAX", nombre: "Baxter International", sector: "Health Care" },
  { ticker: "BBY", nombre: "Best Buy", sector: "Consumer Discretionary" },
  { ticker: "BDX", nombre: "Becton Dickinson", sector: "Health Care" },
  { ticker: "BEN", nombre: "Franklin Resources", sector: "Financials" },
  { ticker: "BF-B", nombre: "Brown–Forman", sector: "Consumer Staples" },
  { ticker: "BG", nombre: "Bunge Global", sector: "Consumer Staples" },
  { ticker: "BIIB", nombre: "Biogen", sector: "Health Care" },
  { ticker: "BKNG", nombre: "Booking Holdings", sector: "Consumer Discretionary" },
  { ticker: "BKR", nombre: "Baker Hughes", sector: "Energy" },
  { ticker: "BLDR", nombre: "Builders FirstSource", sector: "Industrials" },
  { ticker: "BLK", nombre: "BlackRock", sector: "Financials" },
  { ticker: "BMY", nombre: "Bristol Myers Squibb", sector: "Health Care" },
  { ticker: "BNY", nombre: "BNY Mellon", sector: "Financials" },
  { ticker: "BR", nombre: "Broadridge Financial Solutions", sector: "Industrials" },
  { ticker: "BRK-B", nombre: "Berkshire Hathaway", sector: "Financials" },
  { ticker: "BRO", nombre: "Brown & Brown", sector: "Financials" },
  { ticker: "BSX", nombre: "Boston Scientific", sector: "Health Care" },
  { ticker: "BX", nombre: "Blackstone Inc.", sector: "Financials" },
  { ticker: "BXP", nombre: "BXP, Inc.", sector: "Real Estate" },
  { ticker: "C", nombre: "Citigroup", sector: "Financials" },
  { ticker: "CAH", nombre: "Cardinal Health", sector: "Health Care" },
  { ticker: "CARR", nombre: "Carrier Global", sector: "Industrials" },
  { ticker: "CASY", nombre: "Casey's", sector: "Consumer Staples" },
  { ticker: "CAT", nombre: "Caterpillar Inc.", sector: "Industrials" },
  { ticker: "CB", nombre: "Chubb Limited", sector: "Financials" },
  { ticker: "CBOE", nombre: "Cboe Global Markets", sector: "Financials" },
  { ticker: "CBRE", nombre: "CBRE Group", sector: "Real Estate" },
  { ticker: "CCI", nombre: "Crown Castle", sector: "Real Estate" },
  { ticker: "CCL", nombre: "Carnival Corporation", sector: "Consumer Discretionary" },
  { ticker: "CDNS", nombre: "Cadence Design Systems", sector: "Information Technology" },
  { ticker: "CDW", nombre: "CDW Corporation", sector: "Information Technology" },
  { ticker: "CEG", nombre: "Constellation Energy", sector: "Utilities" },
  { ticker: "CF", nombre: "CF Industries", sector: "Materials" },
  { ticker: "CFG", nombre: "Citizens Financial Group", sector: "Financials" },
  { ticker: "CHD", nombre: "Church & Dwight", sector: "Consumer Staples" },
  { ticker: "CHRW", nombre: "C.H. Robinson", sector: "Industrials" },
  { ticker: "CHTR", nombre: "Charter Communications", sector: "Communication Services" },
  { ticker: "CI", nombre: "Cigna", sector: "Health Care" },
  { ticker: "CIEN", nombre: "Ciena", sector: "Information Technology" },
  { ticker: "CINF", nombre: "Cincinnati Financial", sector: "Financials" },
  { ticker: "CL", nombre: "Colgate-Palmolive", sector: "Consumer Staples" },
  { ticker: "CLX", nombre: "Clorox", sector: "Consumer Staples" },
  { ticker: "CMCSA", nombre: "Comcast", sector: "Communication Services" },
  { ticker: "CME", nombre: "CME Group", sector: "Financials" },
  { ticker: "CMG", nombre: "Chipotle Mexican Grill", sector: "Consumer Discretionary" },
  { ticker: "CMI", nombre: "Cummins", sector: "Industrials" },
  { ticker: "CMS", nombre: "CMS Energy", sector: "Utilities" },
  { ticker: "CNC", nombre: "Centene Corporation", sector: "Health Care" },
  { ticker: "CNP", nombre: "CenterPoint Energy", sector: "Utilities" },
  { ticker: "COF", nombre: "Capital One", sector: "Financials" },
  { ticker: "COHR", nombre: "Coherent Corp.", sector: "Information Technology" },
  { ticker: "COIN", nombre: "Coinbase", sector: "Financials" },
  { ticker: "COO", nombre: "Cooper Companies (The)", sector: "Health Care" },
  { ticker: "COP", nombre: "ConocoPhillips", sector: "Energy" },
  { ticker: "COR", nombre: "Cencora", sector: "Health Care" },
  { ticker: "COST", nombre: "Costco", sector: "Consumer Staples" },
  { ticker: "CPAY", nombre: "Corpay", sector: "Financials" },
  { ticker: "CPRT", nombre: "Copart", sector: "Industrials" },
  { ticker: "CPT", nombre: "Camden Property Trust", sector: "Real Estate" },
  { ticker: "CRH", nombre: "CRH plc", sector: "Materials" },
  { ticker: "CRL", nombre: "Charles River Laboratories", sector: "Health Care" },
  { ticker: "CRM", nombre: "Salesforce", sector: "Information Technology" },
  { ticker: "CRWD", nombre: "CrowdStrike", sector: "Information Technology" },
  { ticker: "CSCO", nombre: "Cisco", sector: "Information Technology" },
  { ticker: "CSGP", nombre: "CoStar Group", sector: "Real Estate" },
  { ticker: "CSX", nombre: "CSX Corporation", sector: "Industrials" },
  { ticker: "CTAS", nombre: "Cintas", sector: "Industrials" },
  { ticker: "CTSH", nombre: "Cognizant", sector: "Information Technology" },
  { ticker: "CTVA", nombre: "Corteva", sector: "Materials" },
  { ticker: "CVNA", nombre: "Carvana", sector: "Consumer Discretionary" },
  { ticker: "CVS", nombre: "CVS Health", sector: "Health Care" },
  { ticker: "CVX", nombre: "Chevron Corporation", sector: "Energy" },
  { ticker: "D", nombre: "Dominion Energy", sector: "Utilities" },
  { ticker: "DAL", nombre: "Delta Air Lines", sector: "Industrials" },
  { ticker: "DASH", nombre: "DoorDash", sector: "Consumer Discretionary" },
  { ticker: "DD", nombre: "DuPont", sector: "Industrials" },
  { ticker: "DDOG", nombre: "Datadog", sector: "Information Technology" },
  { ticker: "DE", nombre: "Deere & Company", sector: "Industrials" },
  { ticker: "DECK", nombre: "Deckers Brands", sector: "Consumer Discretionary" },
  { ticker: "DELL", nombre: "Dell Technologies", sector: "Information Technology" },
  { ticker: "DG", nombre: "Dollar General", sector: "Consumer Staples" },
  { ticker: "DGX", nombre: "Quest Diagnostics", sector: "Health Care" },
  { ticker: "DHI", nombre: "D. R. Horton", sector: "Consumer Discretionary" },
  { ticker: "DHR", nombre: "Danaher Corporation", sector: "Health Care" },
  { ticker: "DIS", nombre: "Walt Disney Company (The)", sector: "Communication Services" },
  { ticker: "DLR", nombre: "Digital Realty", sector: "Real Estate" },
  { ticker: "DLTR", nombre: "Dollar Tree", sector: "Consumer Staples" },
  { ticker: "DOC", nombre: "Healthpeak Properties", sector: "Real Estate" },
  { ticker: "DOV", nombre: "Dover Corporation", sector: "Industrials" },
  { ticker: "DOW", nombre: "Dow Inc.", sector: "Materials" },
  { ticker: "DPZ", nombre: "Domino's", sector: "Consumer Discretionary" },
  { ticker: "DRI", nombre: "Darden Restaurants", sector: "Consumer Discretionary" },
  { ticker: "DTE", nombre: "DTE Energy", sector: "Utilities" },
  { ticker: "DUK", nombre: "Duke Energy", sector: "Utilities" },
  { ticker: "DVA", nombre: "DaVita", sector: "Health Care" },
  { ticker: "DVN", nombre: "Devon Energy", sector: "Energy" },
  { ticker: "DXCM", nombre: "Dexcom", sector: "Health Care" },
  { ticker: "EBAY", nombre: "eBay Inc.", sector: "Consumer Discretionary" },
  { ticker: "ECHO", nombre: "EchoStar", sector: "Communication Services" },
  { ticker: "ECL", nombre: "Ecolab", sector: "Materials" },
  { ticker: "ED", nombre: "Consolidated Edison", sector: "Utilities" },
  { ticker: "EFX", nombre: "Equifax", sector: "Industrials" },
  { ticker: "EG", nombre: "Everest Group", sector: "Financials" },
  { ticker: "EIX", nombre: "Edison International", sector: "Utilities" },
  { ticker: "EL", nombre: "Estée Lauder Companies (The)", sector: "Consumer Staples" },
  { ticker: "ELV", nombre: "Elevance Health", sector: "Health Care" },
  { ticker: "EME", nombre: "Emcor", sector: "Industrials" },
  { ticker: "EMR", nombre: "Emerson Electric", sector: "Industrials" },
  { ticker: "EOG", nombre: "EOG Resources", sector: "Energy" },
  { ticker: "EQIX", nombre: "Equinix", sector: "Real Estate" },
  { ticker: "EQT", nombre: "EQT Corporation", sector: "Energy" },
  { ticker: "ERIE", nombre: "Erie Indemnity", sector: "Financials" },
  { ticker: "ES", nombre: "Eversource Energy", sector: "Utilities" },
  { ticker: "ESS", nombre: "Essex Property Trust", sector: "Real Estate" },
  { ticker: "ETN", nombre: "Eaton Corporation", sector: "Industrials" },
  { ticker: "ETR", nombre: "Entergy", sector: "Utilities" },
  { ticker: "EVRG", nombre: "Evergy", sector: "Utilities" },
  { ticker: "EW", nombre: "Edwards Lifesciences", sector: "Health Care" },
  { ticker: "EXC", nombre: "Exelon", sector: "Utilities" },
  { ticker: "EXE", nombre: "Expand Energy", sector: "Energy" },
  { ticker: "EXPD", nombre: "Expeditors International", sector: "Industrials" },
  { ticker: "EXPE", nombre: "Expedia Group", sector: "Consumer Discretionary" },
  { ticker: "EXR", nombre: "Extra Space Storage", sector: "Real Estate" },
  { ticker: "F", nombre: "Ford Motor Company", sector: "Consumer Discretionary" },
  { ticker: "FANG", nombre: "Diamondback Energy", sector: "Energy" },
  { ticker: "FAST", nombre: "Fastenal", sector: "Industrials" },
  { ticker: "FCX", nombre: "Freeport-McMoRan", sector: "Materials" },
  { ticker: "FDS", nombre: "FactSet", sector: "Financials" },
  { ticker: "FDX", nombre: "FedEx", sector: "Industrials" },
  { ticker: "FDXF", nombre: "FedEx Freight", sector: "Industrials" },
  { ticker: "FE", nombre: "FirstEnergy", sector: "Utilities" },
  { ticker: "FERG", nombre: "Ferguson Enterprises", sector: "Industrials" },
  { ticker: "FFIV", nombre: "F5, Inc.", sector: "Information Technology" },
  { ticker: "FICO", nombre: "Fair Isaac", sector: "Information Technology" },
  { ticker: "FIS", nombre: "Fidelity National Information Services", sector: "Financials" },
  { ticker: "FISV", nombre: "Fiserv", sector: "Financials" },
  { ticker: "FITB", nombre: "Fifth Third Bancorp", sector: "Financials" },
  { ticker: "FIX", nombre: "Comfort Systems USA", sector: "Industrials" },
  { ticker: "FLEX", nombre: "Flex Ltd.", sector: "Information Technology" },
  { ticker: "FOX", nombre: "Fox Corporation (Class B)", sector: "Communication Services" },
  { ticker: "FOXA", nombre: "Fox Corporation (Class A)", sector: "Communication Services" },
  { ticker: "FRT", nombre: "Federal Realty Investment Trust", sector: "Real Estate" },
  { ticker: "FSLR", nombre: "First Solar", sector: "Information Technology" },
  { ticker: "FTNT", nombre: "Fortinet", sector: "Information Technology" },
  { ticker: "FTV", nombre: "Fortive", sector: "Industrials" },
  { ticker: "GD", nombre: "General Dynamics", sector: "Industrials" },
  { ticker: "GDDY", nombre: "GoDaddy", sector: "Information Technology" },
  { ticker: "GE", nombre: "GE Aerospace", sector: "Industrials" },
  { ticker: "GEHC", nombre: "GE HealthCare", sector: "Health Care" },
  { ticker: "GEN", nombre: "Gen Digital", sector: "Information Technology" },
  { ticker: "GEV", nombre: "GE Vernova", sector: "Industrials" },
  { ticker: "GILD", nombre: "Gilead Sciences", sector: "Health Care" },
  { ticker: "GIS", nombre: "General Mills", sector: "Consumer Staples" },
  { ticker: "GL", nombre: "Globe Life", sector: "Financials" },
  { ticker: "GLW", nombre: "Corning Inc.", sector: "Information Technology" },
  { ticker: "GM", nombre: "General Motors", sector: "Consumer Discretionary" },
  { ticker: "GNRC", nombre: "Generac", sector: "Industrials" },
  { ticker: "GOOG", nombre: "Alphabet Inc. (Class C)", sector: "Communication Services" },
  { ticker: "GOOGL", nombre: "Alphabet Inc. (Class A)", sector: "Communication Services" },
  { ticker: "GPC", nombre: "Genuine Parts Company", sector: "Consumer Discretionary" },
  { ticker: "GPN", nombre: "Global Payments", sector: "Financials" },
  { ticker: "GRMN", nombre: "Garmin", sector: "Consumer Discretionary" },
  { ticker: "GS", nombre: "Goldman Sachs", sector: "Financials" },
  { ticker: "GWW", nombre: "W. W. Grainger", sector: "Industrials" },
  { ticker: "HAL", nombre: "Halliburton", sector: "Energy" },
  { ticker: "HAS", nombre: "Hasbro", sector: "Consumer Discretionary" },
  { ticker: "HBAN", nombre: "Huntington Bancshares", sector: "Financials" },
  { ticker: "HCA", nombre: "HCA Healthcare", sector: "Health Care" },
  { ticker: "HD", nombre: "Home Depot (The)", sector: "Consumer Discretionary" },
  { ticker: "HIG", nombre: "Hartford (The)", sector: "Financials" },
  { ticker: "HII", nombre: "Huntington Ingalls Industries", sector: "Industrials" },
  { ticker: "HLT", nombre: "Hilton Worldwide", sector: "Consumer Discretionary" },
  { ticker: "HON", nombre: "Honeywell Technologies", sector: "Industrials" },
  { ticker: "HONA", nombre: "Honeywell Aerospace", sector: "Industrials" },
  { ticker: "HOOD", nombre: "Robinhood Markets", sector: "Financials" },
  { ticker: "HPE", nombre: "Hewlett Packard Enterprise", sector: "Information Technology" },
  { ticker: "HPQ", nombre: "HP Inc.", sector: "Information Technology" },
  { ticker: "HRL", nombre: "Hormel Foods", sector: "Consumer Staples" },
  { ticker: "HSIC", nombre: "Henry Schein", sector: "Health Care" },
  { ticker: "HST", nombre: "Host Hotels & Resorts", sector: "Real Estate" },
  { ticker: "HSY", nombre: "Hershey Company (The)", sector: "Consumer Staples" },
  { ticker: "HUBB", nombre: "Hubbell Incorporated", sector: "Industrials" },
  { ticker: "HUM", nombre: "Humana", sector: "Health Care" },
  { ticker: "HWM", nombre: "Howmet Aerospace", sector: "Industrials" },
  { ticker: "IBKR", nombre: "Interactive Brokers", sector: "Financials" },
  { ticker: "IBM", nombre: "IBM", sector: "Information Technology" },
  { ticker: "ICE", nombre: "Intercontinental Exchange", sector: "Financials" },
  { ticker: "IDXX", nombre: "Idexx Laboratories", sector: "Health Care" },
  { ticker: "IEX", nombre: "IDEX Corporation", sector: "Industrials" },
  { ticker: "IFF", nombre: "International Flavors & Fragrances", sector: "Materials" },
  { ticker: "INCY", nombre: "Incyte", sector: "Health Care" },
  { ticker: "INTC", nombre: "Intel", sector: "Information Technology" },
  { ticker: "INTU", nombre: "Intuit", sector: "Information Technology" },
  { ticker: "INVH", nombre: "Invitation Homes", sector: "Real Estate" },
  { ticker: "IP", nombre: "International Paper", sector: "Materials" },
  { ticker: "IQV", nombre: "IQVIA", sector: "Health Care" },
  { ticker: "IR", nombre: "Ingersoll Rand", sector: "Industrials" },
  { ticker: "IRM", nombre: "Iron Mountain", sector: "Real Estate" },
  { ticker: "ISRG", nombre: "Intuitive Surgical", sector: "Health Care" },
  { ticker: "IT", nombre: "Gartner", sector: "Information Technology" },
  { ticker: "ITW", nombre: "Illinois Tool Works", sector: "Industrials" },
  { ticker: "IVZ", nombre: "Invesco", sector: "Financials" },
  { ticker: "J", nombre: "Jacobs Solutions", sector: "Industrials" },
  { ticker: "JBHT", nombre: "J.B. Hunt", sector: "Industrials" },
  { ticker: "JBL", nombre: "Jabil", sector: "Information Technology" },
  { ticker: "JCI", nombre: "Johnson Controls", sector: "Industrials" },
  { ticker: "JKHY", nombre: "Jack Henry & Associates", sector: "Financials" },
  { ticker: "JNJ", nombre: "Johnson & Johnson", sector: "Health Care" },
  { ticker: "JPM", nombre: "JPMorgan Chase", sector: "Financials" },
  { ticker: "KDP", nombre: "Keurig Dr Pepper", sector: "Consumer Staples" },
  { ticker: "KEY", nombre: "KeyCorp", sector: "Financials" },
  { ticker: "KEYS", nombre: "Keysight Technologies", sector: "Information Technology" },
  { ticker: "KHC", nombre: "Kraft Heinz", sector: "Consumer Staples" },
  { ticker: "KIM", nombre: "Kimco Realty", sector: "Real Estate" },
  { ticker: "KKR", nombre: "KKR & Co.", sector: "Financials" },
  { ticker: "KLAC", nombre: "KLA Corporation", sector: "Information Technology" },
  { ticker: "KMB", nombre: "Kimberly-Clark", sector: "Consumer Staples" },
  { ticker: "KMI", nombre: "Kinder Morgan", sector: "Energy" },
  { ticker: "KO", nombre: "Coca-Cola Company (The)", sector: "Consumer Staples" },
  { ticker: "KR", nombre: "Kroger", sector: "Consumer Staples" },
  { ticker: "KVUE", nombre: "Kenvue", sector: "Consumer Staples" },
  { ticker: "L", nombre: "Loews Corporation", sector: "Financials" },
  { ticker: "LDOS", nombre: "Leidos", sector: "Industrials" },
  { ticker: "LEN", nombre: "Lennar", sector: "Consumer Discretionary" },
  { ticker: "LH", nombre: "Labcorp", sector: "Health Care" },
  { ticker: "LHX", nombre: "L3Harris", sector: "Industrials" },
  { ticker: "LII", nombre: "Lennox International", sector: "Industrials" },
  { ticker: "LIN", nombre: "Linde plc", sector: "Materials" },
  { ticker: "LITE", nombre: "Lumentum", sector: "Information Technology" },
  { ticker: "LLY", nombre: "Lilly (Eli)", sector: "Health Care" },
  { ticker: "LMT", nombre: "Lockheed Martin", sector: "Industrials" },
  { ticker: "LNT", nombre: "Alliant Energy", sector: "Utilities" },
  { ticker: "LOW", nombre: "Lowe's", sector: "Consumer Discretionary" },
  { ticker: "LRCX", nombre: "Lam Research", sector: "Information Technology" },
  { ticker: "LULU", nombre: "Lululemon Athletica", sector: "Consumer Discretionary" },
  { ticker: "LUV", nombre: "Southwest Airlines", sector: "Industrials" },
  { ticker: "LVS", nombre: "Las Vegas Sands", sector: "Consumer Discretionary" },
  { ticker: "LYB", nombre: "LyondellBasell", sector: "Materials" },
  { ticker: "LYV", nombre: "Live Nation Entertainment", sector: "Communication Services" },
  { ticker: "MA", nombre: "Mastercard", sector: "Financials" },
  { ticker: "MAA", nombre: "Mid-America Apartment Communities", sector: "Real Estate" },
  { ticker: "MAR", nombre: "Marriott International", sector: "Consumer Discretionary" },
  { ticker: "MAS", nombre: "Masco", sector: "Industrials" },
  { ticker: "MCD", nombre: "McDonald's", sector: "Consumer Discretionary" },
  { ticker: "MCHP", nombre: "Microchip Technology", sector: "Information Technology" },
  { ticker: "MCK", nombre: "McKesson Corporation", sector: "Health Care" },
  { ticker: "MCO", nombre: "Moody's Corporation", sector: "Financials" },
  { ticker: "MDLZ", nombre: "Mondelez International", sector: "Consumer Staples" },
  { ticker: "MDT", nombre: "Medtronic", sector: "Health Care" },
  { ticker: "MET", nombre: "MetLife", sector: "Financials" },
  { ticker: "META", nombre: "Meta Platforms", sector: "Communication Services" },
  { ticker: "MGM", nombre: "MGM Resorts", sector: "Consumer Discretionary" },
  { ticker: "MKC", nombre: "McCormick & Company", sector: "Consumer Staples" },
  { ticker: "MLM", nombre: "Martin Marietta Materials", sector: "Materials" },
  { ticker: "MMM", nombre: "3M", sector: "Industrials" },
  { ticker: "MNST", nombre: "Monster Beverage", sector: "Consumer Staples" },
  { ticker: "MO", nombre: "Altria", sector: "Consumer Staples" },
  { ticker: "MOS", nombre: "Mosaic Company (The)", sector: "Materials" },
  { ticker: "MPC", nombre: "Marathon Petroleum", sector: "Energy" },
  { ticker: "MPWR", nombre: "Monolithic Power Systems", sector: "Information Technology" },
  { ticker: "MRK", nombre: "Merck & Co.", sector: "Health Care" },
  { ticker: "MRNA", nombre: "Moderna", sector: "Health Care" },
  { ticker: "MRSH", nombre: "Marsh McLennan", sector: "Financials" },
  { ticker: "MRVL", nombre: "Marvell Technology", sector: "Information Technology" },
  { ticker: "MS", nombre: "Morgan Stanley", sector: "Financials" },
  { ticker: "MSCI", nombre: "MSCI", sector: "Financials" },
  { ticker: "MSFT", nombre: "Microsoft", sector: "Information Technology" },
  { ticker: "MSI", nombre: "Motorola Solutions", sector: "Information Technology" },
  { ticker: "MTB", nombre: "M&T Bank", sector: "Financials" },
  { ticker: "MTD", nombre: "Mettler Toledo", sector: "Health Care" },
  { ticker: "MU", nombre: "Micron Technology", sector: "Information Technology" },
  { ticker: "NCLH", nombre: "Norwegian Cruise Line Holdings", sector: "Consumer Discretionary" },
  { ticker: "NDAQ", nombre: "Nasdaq, Inc.", sector: "Financials" },
  { ticker: "NDSN", nombre: "Nordson Corporation", sector: "Industrials" },
  { ticker: "NEE", nombre: "NextEra Energy", sector: "Utilities" },
  { ticker: "NEM", nombre: "Newmont", sector: "Materials" },
  { ticker: "NFLX", nombre: "Netflix", sector: "Communication Services" },
  { ticker: "NI", nombre: "NiSource", sector: "Utilities" },
  { ticker: "NKE", nombre: "Nike, Inc.", sector: "Consumer Discretionary" },
  { ticker: "NOC", nombre: "Northrop Grumman", sector: "Industrials" },
  { ticker: "NOW", nombre: "ServiceNow", sector: "Information Technology" },
  { ticker: "NRG", nombre: "NRG Energy", sector: "Utilities" },
  { ticker: "NSC", nombre: "Norfolk Southern", sector: "Industrials" },
  { ticker: "NTAP", nombre: "NetApp", sector: "Information Technology" },
  { ticker: "NTRS", nombre: "Northern Trust", sector: "Financials" },
  { ticker: "NUE", nombre: "Nucor", sector: "Materials" },
  { ticker: "NVDA", nombre: "Nvidia", sector: "Information Technology" },
  { ticker: "NVR", nombre: "NVR, Inc.", sector: "Consumer Discretionary" },
  { ticker: "NWS", nombre: "News Corp (Class B)", sector: "Communication Services" },
  { ticker: "NWSA", nombre: "News Corp (Class A)", sector: "Communication Services" },
  { ticker: "NXPI", nombre: "NXP Semiconductors", sector: "Information Technology" },
  { ticker: "O", nombre: "Realty Income", sector: "Real Estate" },
  { ticker: "ODFL", nombre: "Old Dominion", sector: "Industrials" },
  { ticker: "OKE", nombre: "Oneok", sector: "Energy" },
  { ticker: "OMC", nombre: "Omnicom Group", sector: "Communication Services" },
  { ticker: "ON", nombre: "ON Semiconductor", sector: "Information Technology" },
  { ticker: "ORCL", nombre: "Oracle Corporation", sector: "Information Technology" },
  { ticker: "ORLY", nombre: "O'Reilly Automotive", sector: "Consumer Discretionary" },
  { ticker: "OTIS", nombre: "Otis Worldwide", sector: "Industrials" },
  { ticker: "OXY", nombre: "Occidental Petroleum", sector: "Energy" },
  { ticker: "PANW", nombre: "Palo Alto Networks", sector: "Information Technology" },
  { ticker: "PAYX", nombre: "Paychex", sector: "Industrials" },
  { ticker: "PCAR", nombre: "Paccar", sector: "Industrials" },
  { ticker: "PCG", nombre: "PG&E Corporation", sector: "Utilities" },
  { ticker: "PEG", nombre: "Public Service Enterprise Group", sector: "Utilities" },
  { ticker: "PEP", nombre: "PepsiCo", sector: "Consumer Staples" },
  { ticker: "PFE", nombre: "Pfizer", sector: "Health Care" },
  { ticker: "PFG", nombre: "Principal Financial Group", sector: "Financials" },
  { ticker: "PG", nombre: "Procter & Gamble", sector: "Consumer Staples" },
  { ticker: "PGR", nombre: "Progressive Corporation", sector: "Financials" },
  { ticker: "PH", nombre: "Parker Hannifin", sector: "Industrials" },
  { ticker: "PHM", nombre: "PulteGroup", sector: "Consumer Discretionary" },
  { ticker: "PKG", nombre: "Packaging Corporation of America", sector: "Materials" },
  { ticker: "PLD", nombre: "Prologis", sector: "Real Estate" },
  { ticker: "PLTR", nombre: "Palantir Technologies", sector: "Information Technology" },
  { ticker: "PM", nombre: "Philip Morris International", sector: "Consumer Staples" },
  { ticker: "PNC", nombre: "PNC Financial Services", sector: "Financials" },
  { ticker: "PNR", nombre: "Pentair", sector: "Industrials" },
  { ticker: "PNW", nombre: "Pinnacle West Capital", sector: "Utilities" },
  { ticker: "PODD", nombre: "Insulet Corporation", sector: "Health Care" },
  { ticker: "PPG", nombre: "PPG Industries", sector: "Materials" },
  { ticker: "PPL", nombre: "PPL Corporation", sector: "Utilities" },
  { ticker: "PRU", nombre: "Prudential Financial", sector: "Financials" },
  { ticker: "PSA", nombre: "Public Storage", sector: "Real Estate" },
  { ticker: "PSKY", nombre: "Paramount Skydance Corporation", sector: "Communication Services" },
  { ticker: "PSX", nombre: "Phillips 66", sector: "Energy" },
  { ticker: "PTC", nombre: "PTC Inc.", sector: "Information Technology" },
  { ticker: "PWR", nombre: "Quanta Services", sector: "Industrials" },
  { ticker: "PYPL", nombre: "PayPal", sector: "Financials" },
  { ticker: "Q", nombre: "Qnity Electronics", sector: "Information Technology" },
  { ticker: "QCOM", nombre: "Qualcomm", sector: "Information Technology" },
  { ticker: "RCL", nombre: "Royal Caribbean Group", sector: "Consumer Discretionary" },
  { ticker: "RDDT", nombre: "Reddit", sector: "Communication Services" },
  { ticker: "REG", nombre: "Regency Centers", sector: "Real Estate" },
  { ticker: "REGN", nombre: "Regeneron Pharmaceuticals", sector: "Health Care" },
  { ticker: "RF", nombre: "Regions Financial Corporation", sector: "Financials" },
  { ticker: "RJF", nombre: "Raymond James Financial", sector: "Financials" },
  { ticker: "RL", nombre: "Ralph Lauren Corporation", sector: "Consumer Discretionary" },
  { ticker: "RMD", nombre: "ResMed|", sector: "Health Care" },
  { ticker: "ROK", nombre: "Rockwell Automation", sector: "Industrials" },
  { ticker: "ROL", nombre: "Rollins, Inc.", sector: "Industrials" },
  { ticker: "ROP", nombre: "Roper Technologies", sector: "Information Technology" },
  { ticker: "ROST", nombre: "Ross Stores", sector: "Consumer Discretionary" },
  { ticker: "RSG", nombre: "Republic Services", sector: "Industrials" },
  { ticker: "RTX", nombre: "RTX Corporation", sector: "Industrials" },
  { ticker: "RVTY", nombre: "Revvity", sector: "Health Care" },
  { ticker: "SBAC", nombre: "SBA Communications", sector: "Real Estate" },
  { ticker: "SBUX", nombre: "Starbucks", sector: "Consumer Discretionary" },
  { ticker: "SCHW", nombre: "Charles Schwab Corporation", sector: "Financials" },
  { ticker: "SHW", nombre: "Sherwin-Williams", sector: "Materials" },
  { ticker: "SJM", nombre: "J.M. Smucker Company (The)", sector: "Consumer Staples" },
  { ticker: "SLB", nombre: "Schlumberger", sector: "Energy" },
  { ticker: "SMCI", nombre: "Supermicro", sector: "Information Technology" },
  { ticker: "SNA", nombre: "Snap-on", sector: "Industrials" },
  { ticker: "SNDK", nombre: "Sandisk", sector: "Information Technology" },
  { ticker: "SNPS", nombre: "Synopsys", sector: "Information Technology" },
  { ticker: "SO", nombre: "Southern Company", sector: "Utilities" },
  { ticker: "SOLV", nombre: "Solventum", sector: "Health Care" },
  { ticker: "SPG", nombre: "Simon Property Group", sector: "Real Estate" },
  { ticker: "SPGI", nombre: "S&P Global", sector: "Financials" },
  { ticker: "SRE", nombre: "Sempra", sector: "Utilities" },
  { ticker: "STE", nombre: "Steris", sector: "Health Care" },
  { ticker: "STLD", nombre: "Steel Dynamics", sector: "Materials" },
  { ticker: "STT", nombre: "State Street Corporation", sector: "Financials" },
  { ticker: "STX", nombre: "Seagate Technology", sector: "Information Technology" },
  { ticker: "STZ", nombre: "Constellation Brands", sector: "Consumer Staples" },
  { ticker: "SW", nombre: "Smurfit Westrock", sector: "Materials" },
  { ticker: "SWK", nombre: "Stanley Black & Decker", sector: "Industrials" },
  { ticker: "SWKS", nombre: "Skyworks Solutions", sector: "Information Technology" },
  { ticker: "SYF", nombre: "Synchrony Financial", sector: "Financials" },
  { ticker: "SYK", nombre: "Stryker Corporation", sector: "Health Care" },
  { ticker: "SYY", nombre: "Sysco", sector: "Consumer Staples" },
  { ticker: "T", nombre: "AT&T", sector: "Communication Services" },
  { ticker: "TAP", nombre: "Molson Coors Beverage Company", sector: "Consumer Staples" },
  { ticker: "TDG", nombre: "TransDigm Group", sector: "Industrials" },
  { ticker: "TDY", nombre: "Teledyne Technologies", sector: "Information Technology" },
  { ticker: "TECH", nombre: "Bio-Techne", sector: "Health Care" },
  { ticker: "TEL", nombre: "TE Connectivity", sector: "Information Technology" },
  { ticker: "TER", nombre: "Teradyne", sector: "Information Technology" },
  { ticker: "TFC", nombre: "Truist Financial", sector: "Financials" },
  { ticker: "TGT", nombre: "Target Corporation", sector: "Consumer Staples" },
  { ticker: "TJX", nombre: "TJX Companies", sector: "Consumer Discretionary" },
  { ticker: "TKO", nombre: "TKO Group Holdings", sector: "Communication Services" },
  { ticker: "TMO", nombre: "Thermo Fisher Scientific", sector: "Health Care" },
  { ticker: "TMUS", nombre: "T-Mobile US", sector: "Communication Services" },
  { ticker: "TPL", nombre: "Texas Pacific Land Corporation", sector: "Energy" },
  { ticker: "TPR", nombre: "Tapestry, Inc.", sector: "Consumer Discretionary" },
  { ticker: "TRGP", nombre: "Targa Resources", sector: "Energy" },
  { ticker: "TRMB", nombre: "Trimble Inc.", sector: "Information Technology" },
  { ticker: "TROW", nombre: "T. Rowe Price", sector: "Financials" },
  { ticker: "TRV", nombre: "Travelers Companies (The)", sector: "Financials" },
  { ticker: "TSCO", nombre: "Tractor Supply", sector: "Consumer Discretionary" },
  { ticker: "TSLA", nombre: "Tesla, Inc.", sector: "Consumer Discretionary" },
  { ticker: "TSN", nombre: "Tyson Foods", sector: "Consumer Staples" },
  { ticker: "TT", nombre: "Trane Technologies", sector: "Industrials" },
  { ticker: "TTD", nombre: "Trade Desk (The)", sector: "Communication Services" },
  { ticker: "TTWO", nombre: "Take-Two Interactive", sector: "Communication Services" },
  { ticker: "TXN", nombre: "Texas Instruments", sector: "Information Technology" },
  { ticker: "TXT", nombre: "Textron", sector: "Industrials" },
  { ticker: "TYL", nombre: "Tyler Technologies", sector: "Information Technology" },
  { ticker: "UAL", nombre: "United Airlines Holdings", sector: "Industrials" },
  { ticker: "UBER", nombre: "Uber", sector: "Industrials" },
  { ticker: "UDR", nombre: "UDR, Inc.", sector: "Real Estate" },
  { ticker: "UHS", nombre: "Universal Health Services", sector: "Health Care" },
  { ticker: "ULTA", nombre: "Ulta Beauty", sector: "Consumer Discretionary" },
  { ticker: "UNH", nombre: "UnitedHealth Group", sector: "Health Care" },
  { ticker: "UNP", nombre: "Union Pacific Corporation", sector: "Industrials" },
  { ticker: "UPS", nombre: "United Parcel Service", sector: "Industrials" },
  { ticker: "URI", nombre: "United Rentals", sector: "Industrials" },
  { ticker: "USB", nombre: "U.S. Bancorp", sector: "Financials" },
  { ticker: "V", nombre: "Visa Inc.", sector: "Financials" },
  { ticker: "VEEV", nombre: "Veeva Systems", sector: "Health Care" },
  { ticker: "VICI", nombre: "Vici Properties", sector: "Real Estate" },
  { ticker: "VLO", nombre: "Valero Energy", sector: "Energy" },
  { ticker: "VLTO", nombre: "Veralto", sector: "Industrials" },
  { ticker: "VMC", nombre: "Vulcan Materials Company", sector: "Materials" },
  { ticker: "VMRK", nombre: "Vivmark Residential", sector: "Real Estate" },
  { ticker: "VRSK", nombre: "Verisk Analytics", sector: "Industrials" },
  { ticker: "VRSN", nombre: "Verisign", sector: "Information Technology" },
  { ticker: "VRT", nombre: "Vertiv", sector: "Industrials" },
  { ticker: "VRTX", nombre: "Vertex Pharmaceuticals", sector: "Health Care" },
  { ticker: "VST", nombre: "Vistra Corp.", sector: "Utilities" },
  { ticker: "VTR", nombre: "Ventas", sector: "Real Estate" },
  { ticker: "VTRS", nombre: "Viatris", sector: "Health Care" },
  { ticker: "VZ", nombre: "Verizon", sector: "Communication Services" },
  { ticker: "WAB", nombre: "Wabtec", sector: "Industrials" },
  { ticker: "WAT", nombre: "Waters Corporation", sector: "Health Care" },
  { ticker: "WBD", nombre: "Warner Bros. Discovery", sector: "Communication Services" },
  { ticker: "WDAY", nombre: "Workday, Inc.", sector: "Information Technology" },
  { ticker: "WDC", nombre: "Western Digital", sector: "Information Technology" },
  { ticker: "WEC", nombre: "WEC Energy Group", sector: "Utilities" },
  { ticker: "WELL", nombre: "Welltower", sector: "Real Estate" },
  { ticker: "WFC", nombre: "Wells Fargo", sector: "Financials" },
  { ticker: "WM", nombre: "Waste Management", sector: "Industrials" },
  { ticker: "WMB", nombre: "Williams Companies", sector: "Energy" },
  { ticker: "WMT", nombre: "Walmart", sector: "Consumer Staples" },
  { ticker: "WRB", nombre: "W. R. Berkley Corporation", sector: "Financials" },
  { ticker: "WSM", nombre: "Williams-Sonoma, Inc.", sector: "Consumer Discretionary" },
  { ticker: "WST", nombre: "West Pharmaceutical Services", sector: "Health Care" },
  { ticker: "WTW", nombre: "Willis Towers Watson", sector: "Financials" },
  { ticker: "WY", nombre: "Weyerhaeuser", sector: "Real Estate" },
  { ticker: "WYNN", nombre: "Wynn Resorts", sector: "Consumer Discretionary" },
  { ticker: "XEL", nombre: "Xcel Energy", sector: "Utilities" },
  { ticker: "XOM", nombre: "ExxonMobil", sector: "Energy" },
  { ticker: "XYL", nombre: "Xylem Inc.", sector: "Industrials" },
  { ticker: "XYZ", nombre: "Block, Inc.", sector: "Financials" },
  { ticker: "YUM", nombre: "Yum! Brands", sector: "Consumer Discretionary" },
  { ticker: "ZBH", nombre: "Zimmer Biomet", sector: "Health Care" },
  { ticker: "ZBRA", nombre: "Zebra Technologies", sector: "Information Technology" },
  { ticker: "ZTS", nombre: "Zoetis", sector: "Health Care" },
];

export const POR_TICKER = new Map(UNIVERSO_SP500.map((e) => [e.ticker, e]));
